package kejamart.helper;

/**
 * 
 * @author Kenny Oduor
 * Global settings
 *
 */
public interface Settings {
	
	String SESSION_USER = "SESSION_USER";
	
	String SESSION_NAME = "SESSION_NAME";
	
	String ADMIN_EMAIL = "ADMIN_EMAIL";
	
	String ADMIN_ID = "ADMIN_ID";
	
	String PROFILE_ID = "PROFILE_ID";
	
	String SESSION_DATA = "SESSION_DATA";
	
	String LOGIN_DETAILS = "LOGIN_DETAILS";
	
	String REQUEST_DETAILS = "REQUEST_DETAILS";
	
	String PROPERTY_DETAILS = "PROPERTY_DETAILS";
	
	String VIEW_DETAILS = "VIEW_DETAILS";	
	
	String PROPERTY_NAME = "PROPERTY_NAME";
	
	String PROPERTY_UNIT = "PROPERTY_UNIT";	
	
	String PICTURE_DETAILS = "PICTURE_DETAILS";	
	
	String MESSAGE_ID = "MESSAGE_ID";	
	
	String SYSTEMDIRECTORY = "SYSTEMDIRECTORY";
	
	String CAPTCHA = "CAPTCHA";
	
	String PASS = "PASS";
	
	String ROOTPASSWORD = "ROOTPASSWORD";
	
	String IMAGEDIRECTORY = "IMAGEDIRECTORY";
	
	String USERPHONECONTACTS = "USERPHONECONTACTS";
	
	String USERADDRESSCONTACTS = "USERADDRESSCONTACTS";
	
	String USERINTERESTS = "USERINTERESTS";
	
	String ROOT_USER = "root";
	
	String ADMIN_LOGIN = "ADMIN_LOGIN";
	
	String SUPER_ADMIN_LOGIN = "SUPER_ADMIN_LOGIN";
	
	String ADMIN_LOGIN_DETAILS = "ADMIN_LOGIN_DETAILS";
	
	String ADMIN_USERS = "ADMIN_USERS";
	
	String USER_CITY_NAME = "USER_CITY_NAME";
		
	String USER_CART = "USER_CART";
	
	String USER_NUMBER_OF_UNREAD_MAILS="USER_NUMBER_OF_UNREAD_MAILS";
}
